// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: api/proto/pty.proto

package pty

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PtyStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cwd   string            `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Shell string            `protobuf:"bytes,3,opt,name=shell,proto3" json:"shell,omitempty"`
	Env   map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cols  uint32            `protobuf:"varint,5,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows  uint32            `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`
}

func (x *PtyStartRequest) Reset() {
	*x = PtyStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_pty_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtyStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyStartRequest) ProtoMessage() {}

func (x *PtyStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pty_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyStartRequest.ProtoReflect.Descriptor instead.
func (*PtyStartRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pty_proto_rawDescGZIP(), []int{0}
}

func (x *PtyStartRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PtyStartRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *PtyStartRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *PtyStartRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *PtyStartRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PtyStartRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type PtyStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PtyStartResponse) Reset() {
	*x = PtyStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_pty_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtyStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyStartResponse) ProtoMessage() {}

func (x *PtyStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pty_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyStartResponse.ProtoReflect.Descriptor instead.
func (*PtyStartResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pty_proto_rawDescGZIP(), []int{1}
}

func (x *PtyStartResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PtyStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PtyStreamRequest) Reset() {
	*x = PtyStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_pty_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtyStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyStreamRequest) ProtoMessage() {}

func (x *PtyStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pty_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyStreamRequest.ProtoReflect.Descriptor instead.
func (*PtyStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pty_proto_rawDescGZIP(), []int{2}
}

func (x *PtyStreamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PtyDataEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PtyDataEvent) Reset() {
	*x = PtyDataEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_pty_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtyDataEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyDataEvent) ProtoMessage() {}

func (x *PtyDataEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pty_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyDataEvent.ProtoReflect.Descriptor instead.
func (*PtyDataEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_pty_proto_rawDescGZIP(), []int{3}
}

func (x *PtyDataEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PtyDataEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PtyExitEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExitCode int32  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Signal   string `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`
}

func (x *PtyExitEvent) Reset() {
	*x = PtyExitEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_pty_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtyExitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyExitEvent) ProtoMessage() {}

func (x *PtyExitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pty_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyExitEvent.ProtoReflect.Descriptor instead.
func (*PtyExitEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_pty_proto_rawDescGZIP(), []int{4}
}

func (x *PtyExitEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PtyExitEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *PtyExitEvent) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type PtyStreamEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Event:
	//
	//	*PtyStreamEvent_Data
	//	*PtyStreamEvent_Exit
	Event isPtyStreamEvent_Event `protobuf_oneof:"event"`
}

func (x *PtyStreamEvent) Reset() {
	*x = PtyStreamEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_pty_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtyStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyStreamEvent) ProtoMessage() {}

func (x *PtyStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pty_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyStreamEvent.ProtoReflect.Descriptor instead.
func (*PtyStreamEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_pty_proto_rawDescGZIP(), []int{5}
}

func (x *PtyStreamEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (m *PtyStreamEvent) GetEvent() isPtyStreamEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *PtyStreamEvent) GetData() *PtyDataEvent {
	if x, ok := x.GetEvent().(*PtyStreamEvent_Data); ok {
		return x.Data
	}
	return nil
}

func (x *PtyStreamEvent) GetExit() *PtyExitEvent {
	if x, ok := x.GetEvent().(*PtyStreamEvent_Exit); ok {
		return x.Exit
	}
	return nil
}

type isPtyStreamEvent_Event interface {
	isPtyStreamEvent_Event()
}

type PtyStreamEvent_Data struct {
	Data *PtyDataEvent `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type PtyStreamEvent_Exit struct {
	Exit *PtyExitEvent `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*PtyStreamEvent_Data) isPtyStreamEvent_Event() {}

func (*PtyStreamEvent_Exit) isPtyStreamEvent_Event() {}

type PtyWriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PtyWriteRequest) Reset() {
	*x = PtyWriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_pty_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtyWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyWriteRequest) ProtoMessage() {}

func (x *PtyWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pty_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyWriteRequest.ProtoReflect.Descriptor instead.
func (*PtyWriteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pty_proto_rawDescGZIP(), []int{6}
}

func (x *PtyWriteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PtyWriteRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PtyResizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cols uint32 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows uint32 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
}

func (x *PtyResizeRequest) Reset() {
	*x = PtyResizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_pty_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtyResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyResizeRequest) ProtoMessage() {}

func (x *PtyResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pty_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyResizeRequest.ProtoReflect.Descriptor instead.
func (*PtyResizeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pty_proto_rawDescGZIP(), []int{7}
}

func (x *PtyResizeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PtyResizeRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PtyResizeRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type PtyKillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PtyKillRequest) Reset() {
	*x = PtyKillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_pty_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtyKillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyKillRequest) ProtoMessage() {}

func (x *PtyKillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pty_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyKillRequest.ProtoReflect.Descriptor instead.
func (*PtyKillRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pty_proto_rawDescGZIP(), []int{8}
}

func (x *PtyKillRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_proto_pty_proto protoreflect.FileDescriptor

var file_api_proto_pty_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x74,
	0x79, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe1,
	0x01, 0x0a, 0x0f, 0x50, 0x74, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x63, 0x77, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x36, 0x0a, 0x03, 0x65, 0x6e,
	0x76, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68,
	0x2e, 0x70, 0x74, 0x79, 0x2e, 0x50, 0x74, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x65,
	0x6e, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x6e,
	0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x22, 0x0a, 0x10, 0x50, 0x74, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x50, 0x74, 0x79, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x0c, 0x50, 0x74,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x53,
	0x0a, 0x0c, 0x50, 0x74, 0x79, 0x45, 0x78, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x22, 0x89, 0x01, 0x0a, 0x0e, 0x50, 0x74, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x74,
	0x79, 0x2e, 0x50, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x04, 0x65, 0x78, 0x69, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x74,
	0x79, 0x2e, 0x50, 0x74, 0x79, 0x45, 0x78, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x04, 0x65, 0x78, 0x69, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22,
	0x35, 0x0a, 0x0f, 0x50, 0x74, 0x79, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x10, 0x50, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f,
	0x77, 0x73, 0x22, 0x20, 0x0a, 0x0e, 0x50, 0x74, 0x79, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x32, 0xe3, 0x02, 0x0a, 0x0a, 0x50, 0x74, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x74, 0x79, 0x12,
	0x1b, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x74, 0x79, 0x2e, 0x50, 0x74, 0x79,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x65,
	0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x74, 0x79, 0x2e, 0x50, 0x74, 0x79, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0d, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x50, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x2e, 0x65, 0x6d,
	0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x74, 0x79, 0x2e, 0x50, 0x74, 0x79, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x65, 0x6d, 0x64, 0x61,
	0x73, 0x68, 0x2e, 0x70, 0x74, 0x79, 0x2e, 0x50, 0x74, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x12, 0x3f, 0x0a, 0x08, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x50, 0x74, 0x79, 0x12, 0x1b, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x74, 0x79,
	0x2e, 0x50, 0x74, 0x79, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x41, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x69,
	0x7a, 0x65, 0x50, 0x74, 0x79, 0x12, 0x1c, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70,
	0x74, 0x79, 0x2e, 0x50, 0x74, 0x79, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3d, 0x0a, 0x07, 0x4b,
	0x69, 0x6c, 0x6c, 0x50, 0x74, 0x79, 0x12, 0x1a, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e,
	0x70, 0x74, 0x79, 0x2e, 0x50, 0x74, 0x79, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x68,
	0x71, 0x2f, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x74, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_pty_proto_rawDescOnce sync.Once
	file_api_proto_pty_proto_rawDescData = file_api_proto_pty_proto_rawDesc
)

func file_api_proto_pty_proto_rawDescGZIP() []byte {
	file_api_proto_pty_proto_rawDescOnce.Do(func() {
		file_api_proto_pty_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_pty_proto_rawDescData)
	})
	return file_api_proto_pty_proto_rawDescData
}

var file_api_proto_pty_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_pty_proto_goTypes = []interface{}{
	(*PtyStartRequest)(nil),  // 0: emdash.pty.PtyStartRequest
	(*PtyStartResponse)(nil), // 1: emdash.pty.PtyStartResponse
	(*PtyStreamRequest)(nil), // 2: emdash.pty.PtyStreamRequest
	(*PtyDataEvent)(nil),     // 3: emdash.pty.PtyDataEvent
	(*PtyExitEvent)(nil),     // 4: emdash.pty.PtyExitEvent
	(*PtyStreamEvent)(nil),   // 5: emdash.pty.PtyStreamEvent
	(*PtyWriteRequest)(nil),  // 6: emdash.pty.PtyWriteRequest
	(*PtyResizeRequest)(nil), // 7: emdash.pty.PtyResizeRequest
	(*PtyKillRequest)(nil),   // 8: emdash.pty.PtyKillRequest
	nil,                      // 9: emdash.pty.PtyStartRequest.EnvEntry
	(*emptypb.Empty)(nil),    // 10: google.protobuf.Empty
}
var file_api_proto_pty_proto_depIdxs = []int32{
	9,  // 0: emdash.pty.PtyStartRequest.env:type_name -> emdash.pty.PtyStartRequest.EnvEntry
	3,  // 1: emdash.pty.PtyStreamEvent.data:type_name -> emdash.pty.PtyDataEvent
	4,  // 2: emdash.pty.PtyStreamEvent.exit:type_name -> emdash.pty.PtyExitEvent
	0,  // 3: emdash.pty.PtyService.StartPty:input_type -> emdash.pty.PtyStartRequest
	2,  // 4: emdash.pty.PtyService.StreamPtyData:input_type -> emdash.pty.PtyStreamRequest
	6,  // 5: emdash.pty.PtyService.WritePty:input_type -> emdash.pty.PtyWriteRequest
	7,  // 6: emdash.pty.PtyService.ResizePty:input_type -> emdash.pty.PtyResizeRequest
	8,  // 7: emdash.pty.PtyService.KillPty:input_type -> emdash.pty.PtyKillRequest
	1,  // 8: emdash.pty.PtyService.StartPty:output_type -> emdash.pty.PtyStartResponse
	5,  // 9: emdash.pty.PtyService.StreamPtyData:output_type -> emdash.pty.PtyStreamEvent
	10, // 10: emdash.pty.PtyService.WritePty:output_type -> google.protobuf.Empty
	10, // 11: emdash.pty.PtyService.ResizePty:output_type -> google.protobuf.Empty
	10, // 12: emdash.pty.PtyService.KillPty:output_type -> google.protobuf.Empty
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_pty_proto_init() }
func file_api_proto_pty_proto_init() {
	if File_api_proto_pty_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_pty_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtyStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_pty_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtyStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_pty_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtyStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_pty_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtyDataEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_pty_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtyExitEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_pty_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtyStreamEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_pty_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtyWriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_pty_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtyResizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_pty_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtyKillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_pty_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*PtyStreamEvent_Data)(nil),
		(*PtyStreamEvent_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_pty_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_pty_proto_goTypes,
		DependencyIndexes: file_api_proto_pty_proto_depIdxs,
		MessageInfos:      file_api_proto_pty_proto_msgTypes,
	}.Build()
	File_api_proto_pty_proto = out.File
	file_api_proto_pty_proto_rawDesc = nil
	file_api_proto_pty_proto_goTypes = nil
	file_api_proto_pty_proto_depIdxs = nil
}
