// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: api/proto/pty.proto

package pty

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PtyServiceClient is the client API for PtyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PtyServiceClient interface {
	StartPty(ctx context.Context, in *PtyStartRequest, opts ...grpc.CallOption) (*PtyStartResponse, error)
	StreamPtyData(ctx context.Context, in *PtyStreamRequest, opts ...grpc.CallOption) (PtyService_StreamPtyDataClient, error)
	WritePty(ctx context.Context, in *PtyWriteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResizePty(ctx context.Context, in *PtyResizeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	KillPty(ctx context.Context, in *PtyKillRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type ptyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPtyServiceClient(cc grpc.ClientConnInterface) PtyServiceClient {
	return &ptyServiceClient{cc}
}

func (c *ptyServiceClient) StartPty(ctx context.Context, in *PtyStartRequest, opts ...grpc.CallOption) (*PtyStartResponse, error) {
	out := new(PtyStartResponse)
	err := c.cc.Invoke(ctx, "/emdash.pty.PtyService/StartPty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ptyServiceClient) StreamPtyData(ctx context.Context, in *PtyStreamRequest, opts ...grpc.CallOption) (PtyService_StreamPtyDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &PtyService_ServiceDesc.Streams[0], "/emdash.pty.PtyService/StreamPtyData", opts...)
	if err != nil {
		return nil, err
	}
	x := &ptyServiceStreamPtyDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PtyService_StreamPtyDataClient interface {
	Recv() (*PtyStreamEvent, error)
	grpc.ClientStream
}

type ptyServiceStreamPtyDataClient struct {
	grpc.ClientStream
}

func (x *ptyServiceStreamPtyDataClient) Recv() (*PtyStreamEvent, error) {
	m := new(PtyStreamEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ptyServiceClient) WritePty(ctx context.Context, in *PtyWriteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/emdash.pty.PtyService/WritePty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ptyServiceClient) ResizePty(ctx context.Context, in *PtyResizeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/emdash.pty.PtyService/ResizePty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ptyServiceClient) KillPty(ctx context.Context, in *PtyKillRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/emdash.pty.PtyService/KillPty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PtyServiceServer is the server API for PtyService service.
// All implementations must embed UnimplementedPtyServiceServer
// for forward compatibility
type PtyServiceServer interface {
	StartPty(context.Context, *PtyStartRequest) (*PtyStartResponse, error)
	StreamPtyData(*PtyStreamRequest, PtyService_StreamPtyDataServer) error
	WritePty(context.Context, *PtyWriteRequest) (*emptypb.Empty, error)
	ResizePty(context.Context, *PtyResizeRequest) (*emptypb.Empty, error)
	KillPty(context.Context, *PtyKillRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPtyServiceServer()
}

// UnimplementedPtyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPtyServiceServer struct {
}

func (UnimplementedPtyServiceServer) StartPty(context.Context, *PtyStartRequest) (*PtyStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPty not implemented")
}
func (UnimplementedPtyServiceServer) StreamPtyData(*PtyStreamRequest, PtyService_StreamPtyDataServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPtyData not implemented")
}
func (UnimplementedPtyServiceServer) WritePty(context.Context, *PtyWriteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WritePty not implemented")
}
func (UnimplementedPtyServiceServer) ResizePty(context.Context, *PtyResizeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResizePty not implemented")
}
func (UnimplementedPtyServiceServer) KillPty(context.Context, *PtyKillRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillPty not implemented")
}
func (UnimplementedPtyServiceServer) mustEmbedUnimplementedPtyServiceServer() {}

// UnsafePtyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PtyServiceServer will
// result in compilation errors.
type UnsafePtyServiceServer interface {
	mustEmbedUnimplementedPtyServiceServer()
}

func RegisterPtyServiceServer(s grpc.ServiceRegistrar, srv PtyServiceServer) {
	s.RegisterService(&PtyService_ServiceDesc, srv)
}

func _PtyService_StartPty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PtyStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtyServiceServer).StartPty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.pty.PtyService/StartPty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtyServiceServer).StartPty(ctx, req.(*PtyStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PtyService_StreamPtyData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PtyStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PtyServiceServer).StreamPtyData(m, &ptyServiceStreamPtyDataServer{stream})
}

type PtyService_StreamPtyDataServer interface {
	Send(*PtyStreamEvent) error
	grpc.ServerStream
}

type ptyServiceStreamPtyDataServer struct {
	grpc.ServerStream
}

func (x *ptyServiceStreamPtyDataServer) Send(m *PtyStreamEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PtyService_WritePty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PtyWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtyServiceServer).WritePty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.pty.PtyService/WritePty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtyServiceServer).WritePty(ctx, req.(*PtyWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PtyService_ResizePty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PtyResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtyServiceServer).ResizePty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.pty.PtyService/ResizePty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtyServiceServer).ResizePty(ctx, req.(*PtyResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PtyService_KillPty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PtyKillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtyServiceServer).KillPty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.pty.PtyService/KillPty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtyServiceServer).KillPty(ctx, req.(*PtyKillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PtyService_ServiceDesc is the grpc.ServiceDesc for PtyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PtyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emdash.pty.PtyService",
	HandlerType: (*PtyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartPty",
			Handler:    _PtyService_StartPty_Handler,
		},
		{
			MethodName: "WritePty",
			Handler:    _PtyService_WritePty_Handler,
		},
		{
			MethodName: "ResizePty",
			Handler:    _PtyService_ResizePty_Handler,
		},
		{
			MethodName: "KillPty",
			Handler:    _PtyService_KillPty_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPtyData",
			Handler:       _PtyService_StreamPtyData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/pty.proto",
}
