// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: api/proto/git.proto

package git

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiffType int32

const (
	DiffType_DIFF_TYPE_UNSPECIFIED DiffType = 0
	DiffType_DIFF_TYPE_CONTEXT     DiffType = 1
	DiffType_DIFF_TYPE_ADD         DiffType = 2
	DiffType_DIFF_TYPE_DEL         DiffType = 3
)

// Enum value maps for DiffType.
var (
	DiffType_name = map[int32]string{
		0: "DIFF_TYPE_UNSPECIFIED",
		1: "DIFF_TYPE_CONTEXT",
		2: "DIFF_TYPE_ADD",
		3: "DIFF_TYPE_DEL",
	}
	DiffType_value = map[string]int32{
		"DIFF_TYPE_UNSPECIFIED": 0,
		"DIFF_TYPE_CONTEXT":     1,
		"DIFF_TYPE_ADD":         2,
		"DIFF_TYPE_DEL":         3,
	}
)

func (x DiffType) Enum() *DiffType {
	p := new(DiffType)
	*p = x
	return p
}

func (x DiffType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiffType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_git_proto_enumTypes[0].Descriptor()
}

func (DiffType) Type() protoreflect.EnumType {
	return &file_api_proto_git_proto_enumTypes[0]
}

func (x DiffType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiffType.Descriptor instead.
func (DiffType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_git_proto_rawDescGZIP(), []int{0}
}

type RevertAction int32

const (
	RevertAction_REVERT_ACTION_UNSPECIFIED RevertAction = 0
	RevertAction_REVERT_ACTION_UNSTAGED    RevertAction = 1
	RevertAction_REVERT_ACTION_REVERTED    RevertAction = 2
)

// Enum value maps for RevertAction.
var (
	RevertAction_name = map[int32]string{
		0: "REVERT_ACTION_UNSPECIFIED",
		1: "REVERT_ACTION_UNSTAGED",
		2: "REVERT_ACTION_REVERTED",
	}
	RevertAction_value = map[string]int32{
		"REVERT_ACTION_UNSPECIFIED": 0,
		"REVERT_ACTION_UNSTAGED":    1,
		"REVERT_ACTION_REVERTED":    2,
	}
)

func (x RevertAction) Enum() *RevertAction {
	p := new(RevertAction)
	*p = x
	return p
}

func (x RevertAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RevertAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_git_proto_enumTypes[1].Descriptor()
}

func (RevertAction) Type() protoreflect.EnumType {
	return &file_api_proto_git_proto_enumTypes[1]
}

func (x RevertAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RevertAction.Descriptor instead.
func (RevertAction) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_git_proto_rawDescGZIP(), []int{1}
}

type GitChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Status    string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Additions int32  `protobuf:"varint,3,opt,name=additions,proto3" json:"additions,omitempty"`
	Deletions int32  `protobuf:"varint,4,opt,name=deletions,proto3" json:"deletions,omitempty"`
	IsStaged  bool   `protobuf:"varint,5,opt,name=is_staged,json=isStaged,proto3" json:"is_staged,omitempty"`
}

func (x *GitChange) Reset() {
	*x = GitChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_git_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GitChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitChange) ProtoMessage() {}

func (x *GitChange) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_git_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitChange.ProtoReflect.Descriptor instead.
func (*GitChange) Descriptor() ([]byte, []int) {
	return file_api_proto_git_proto_rawDescGZIP(), []int{0}
}

func (x *GitChange) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GitChange) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GitChange) GetAdditions() int32 {
	if x != nil {
		return x.Additions
	}
	return 0
}

func (x *GitChange) GetDeletions() int32 {
	if x != nil {
		return x.Deletions
	}
	return 0
}

func (x *GitChange) GetIsStaged() bool {
	if x != nil {
		return x.IsStaged
	}
	return false
}

type FileDiffLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left  *string  `protobuf:"bytes,1,opt,name=left,proto3,oneof" json:"left,omitempty"`
	Right *string  `protobuf:"bytes,2,opt,name=right,proto3,oneof" json:"right,omitempty"`
	Type  DiffType `protobuf:"varint,3,opt,name=type,proto3,enum=emdash.git.DiffType" json:"type,omitempty"`
}

func (x *FileDiffLine) Reset() {
	*x = FileDiffLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_git_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDiffLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDiffLine) ProtoMessage() {}

func (x *FileDiffLine) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_git_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDiffLine.ProtoReflect.Descriptor instead.
func (*FileDiffLine) Descriptor() ([]byte, []int) {
	return file_api_proto_git_proto_rawDescGZIP(), []int{1}
}

func (x *FileDiffLine) GetLeft() string {
	if x != nil && x.Left != nil {
		return *x.Left
	}
	return ""
}

func (x *FileDiffLine) GetRight() string {
	if x != nil && x.Right != nil {
		return *x.Right
	}
	return ""
}

func (x *FileDiffLine) GetType() DiffType {
	if x != nil {
		return x.Type
	}
	return DiffType_DIFF_TYPE_UNSPECIFIED
}

type GetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkspacePath string `protobuf:"bytes,1,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_git_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_git_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_git_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Changes []*GitChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_git_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_git_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_git_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetChanges() []*GitChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type StageFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkspacePath string `protobuf:"bytes,1,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
	FilePath      string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *StageFileRequest) Reset() {
	*x = StageFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_git_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageFileRequest) ProtoMessage() {}

func (x *StageFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_git_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageFileRequest.ProtoReflect.Descriptor instead.
func (*StageFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_git_proto_rawDescGZIP(), []int{4}
}

func (x *StageFileRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

func (x *StageFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type RevertFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkspacePath string `protobuf:"bytes,1,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
	FilePath      string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *RevertFileRequest) Reset() {
	*x = RevertFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_git_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevertFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertFileRequest) ProtoMessage() {}

func (x *RevertFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_git_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertFileRequest.ProtoReflect.Descriptor instead.
func (*RevertFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_git_proto_rawDescGZIP(), []int{5}
}

func (x *RevertFileRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

func (x *RevertFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type RevertFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action RevertAction `protobuf:"varint,1,opt,name=action,proto3,enum=emdash.git.RevertAction" json:"action,omitempty"`
}

func (x *RevertFileResponse) Reset() {
	*x = RevertFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_git_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevertFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertFileResponse) ProtoMessage() {}

func (x *RevertFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_git_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertFileResponse.ProtoReflect.Descriptor instead.
func (*RevertFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_git_proto_rawDescGZIP(), []int{6}
}

func (x *RevertFileResponse) GetAction() RevertAction {
	if x != nil {
		return x.Action
	}
	return RevertAction_REVERT_ACTION_UNSPECIFIED
}

type GetFileDiffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkspacePath string `protobuf:"bytes,1,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
	FilePath      string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *GetFileDiffRequest) Reset() {
	*x = GetFileDiffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_git_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileDiffRequest) ProtoMessage() {}

func (x *GetFileDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_git_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileDiffRequest.ProtoReflect.Descriptor instead.
func (*GetFileDiffRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_git_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileDiffRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

func (x *GetFileDiffRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type GetFileDiffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lines []*FileDiffLine `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
}

func (x *GetFileDiffResponse) Reset() {
	*x = GetFileDiffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_git_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileDiffResponse) ProtoMessage() {}

func (x *GetFileDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_git_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileDiffResponse.ProtoReflect.Descriptor instead.
func (*GetFileDiffResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_git_proto_rawDescGZIP(), []int{8}
}

func (x *GetFileDiffResponse) GetLines() []*FileDiffLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

var File_api_proto_git_proto protoreflect.FileDescriptor

var file_api_proto_git_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x69, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x69,
	0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90,
	0x01, 0x0a, 0x09, 0x47, 0x69, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x64, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x64, 0x22, 0x7f, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x69, 0x66, 0x66, 0x4c, 0x69, 0x6e,
	0x65, 0x12, 0x17, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x69, 0x74,
	0x2e, 0x44, 0x69, 0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x22, 0x39, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x44, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x69, 0x74,
	0x2e, 0x47, 0x69, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x73, 0x22, 0x56, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x57, 0x0a, 0x11, 0x52,
	0x65, 0x76, 0x65, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x25, 0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x22, 0x46, 0x0a, 0x12, 0x52, 0x65, 0x76, 0x65, 0x72, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x65, 0x6d, 0x64,
	0x61, 0x73, 0x68, 0x2e, 0x67, 0x69, 0x74, 0x2e, 0x52, 0x65, 0x76, 0x65, 0x72, 0x74, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x58, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x45, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a,
	0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65,
	0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x69, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x69,
	0x66, 0x66, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2a, 0x62, 0x0a,
	0x08, 0x44, 0x69, 0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x49, 0x46,
	0x46, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x44, 0x49, 0x46, 0x46, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x44,
	0x49, 0x46, 0x46, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x44, 0x44, 0x10, 0x02, 0x12, 0x11,
	0x0a, 0x0d, 0x44, 0x49, 0x46, 0x46, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45, 0x4c, 0x10,
	0x03, 0x2a, 0x65, 0x0a, 0x0c, 0x52, 0x65, 0x76, 0x65, 0x72, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1d, 0x0a, 0x19, 0x52, 0x45, 0x56, 0x45, 0x52, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x1a, 0x0a, 0x16, 0x52, 0x45, 0x56, 0x45, 0x52, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x54, 0x41, 0x47, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16,
	0x52, 0x45, 0x56, 0x45, 0x52, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45,
	0x56, 0x45, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x32, 0xb6, 0x02, 0x0a, 0x0a, 0x47, 0x69, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x69,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x69, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x41, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1c,
	0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x69, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x4b, 0x0a, 0x0a, 0x52, 0x65, 0x76, 0x65, 0x72, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x69, 0x74, 0x2e,
	0x52, 0x65, 0x76, 0x65, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x69, 0x74, 0x2e, 0x52,
	0x65, 0x76, 0x65, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x69, 0x66, 0x66,
	0x12, 0x1e, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x69, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x69, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x68, 0x71, 0x2f, 0x65, 0x6d, 0x64, 0x61, 0x73, 0x68, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_git_proto_rawDescOnce sync.Once
	file_api_proto_git_proto_rawDescData = file_api_proto_git_proto_rawDesc
)

func file_api_proto_git_proto_rawDescGZIP() []byte {
	file_api_proto_git_proto_rawDescOnce.Do(func() {
		file_api_proto_git_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_git_proto_rawDescData)
	})
	return file_api_proto_git_proto_rawDescData
}

var file_api_proto_git_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_git_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_git_proto_goTypes = []interface{}{
	(DiffType)(0),               // 0: emdash.git.DiffType
	(RevertAction)(0),           // 1: emdash.git.RevertAction
	(*GitChange)(nil),           // 2: emdash.git.GitChange
	(*FileDiffLine)(nil),        // 3: emdash.git.FileDiffLine
	(*GetStatusRequest)(nil),    // 4: emdash.git.GetStatusRequest
	(*GetStatusResponse)(nil),   // 5: emdash.git.GetStatusResponse
	(*StageFileRequest)(nil),    // 6: emdash.git.StageFileRequest
	(*RevertFileRequest)(nil),   // 7: emdash.git.RevertFileRequest
	(*RevertFileResponse)(nil),  // 8: emdash.git.RevertFileResponse
	(*GetFileDiffRequest)(nil),  // 9: emdash.git.GetFileDiffRequest
	(*GetFileDiffResponse)(nil), // 10: emdash.git.GetFileDiffResponse
	(*emptypb.Empty)(nil),       // 11: google.protobuf.Empty
}
var file_api_proto_git_proto_depIdxs = []int32{
	0,  // 0: emdash.git.FileDiffLine.type:type_name -> emdash.git.DiffType
	2,  // 1: emdash.git.GetStatusResponse.changes:type_name -> emdash.git.GitChange
	1,  // 2: emdash.git.RevertFileResponse.action:type_name -> emdash.git.RevertAction
	3,  // 3: emdash.git.GetFileDiffResponse.lines:type_name -> emdash.git.FileDiffLine
	4,  // 4: emdash.git.GitService.GetStatus:input_type -> emdash.git.GetStatusRequest
	6,  // 5: emdash.git.GitService.StageFile:input_type -> emdash.git.StageFileRequest
	7,  // 6: emdash.git.GitService.RevertFile:input_type -> emdash.git.RevertFileRequest
	9,  // 7: emdash.git.GitService.GetFileDiff:input_type -> emdash.git.GetFileDiffRequest
	5,  // 8: emdash.git.GitService.GetStatus:output_type -> emdash.git.GetStatusResponse
	11, // 9: emdash.git.GitService.StageFile:output_type -> google.protobuf.Empty
	8,  // 10: emdash.git.GitService.RevertFile:output_type -> emdash.git.RevertFileResponse
	10, // 11: emdash.git.GitService.GetFileDiff:output_type -> emdash.git.GetFileDiffResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_git_proto_init() }
func file_api_proto_git_proto_init() {
	if File_api_proto_git_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_git_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GitChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_git_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileDiffLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_git_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_git_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_git_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_git_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevertFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_git_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevertFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_git_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileDiffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_git_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileDiffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_git_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_git_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_git_proto_goTypes,
		DependencyIndexes: file_api_proto_git_proto_depIdxs,
		EnumInfos:         file_api_proto_git_proto_enumTypes,
		MessageInfos:      file_api_proto_git_proto_msgTypes,
	}.Build()
	File_api_proto_git_proto = out.File
	file_api_proto_git_proto_rawDesc = nil
	file_api_proto_git_proto_goTypes = nil
	file_api_proto_git_proto_depIdxs = nil
}
