// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: api/proto/git.proto

package git

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GitServiceClient is the client API for GitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GitServiceClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	StageFile(ctx context.Context, in *StageFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RevertFile(ctx context.Context, in *RevertFileRequest, opts ...grpc.CallOption) (*RevertFileResponse, error)
	GetFileDiff(ctx context.Context, in *GetFileDiffRequest, opts ...grpc.CallOption) (*GetFileDiffResponse, error)
}

type gitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGitServiceClient(cc grpc.ClientConnInterface) GitServiceClient {
	return &gitServiceClient{cc}
}

func (c *gitServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/emdash.git.GitService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) StageFile(ctx context.Context, in *StageFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/emdash.git.GitService/StageFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) RevertFile(ctx context.Context, in *RevertFileRequest, opts ...grpc.CallOption) (*RevertFileResponse, error) {
	out := new(RevertFileResponse)
	err := c.cc.Invoke(ctx, "/emdash.git.GitService/RevertFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) GetFileDiff(ctx context.Context, in *GetFileDiffRequest, opts ...grpc.CallOption) (*GetFileDiffResponse, error) {
	out := new(GetFileDiffResponse)
	err := c.cc.Invoke(ctx, "/emdash.git.GitService/GetFileDiff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitServiceServer is the server API for GitService service.
// All implementations must embed UnimplementedGitServiceServer
// for forward compatibility
type GitServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	StageFile(context.Context, *StageFileRequest) (*emptypb.Empty, error)
	RevertFile(context.Context, *RevertFileRequest) (*RevertFileResponse, error)
	GetFileDiff(context.Context, *GetFileDiffRequest) (*GetFileDiffResponse, error)
	mustEmbedUnimplementedGitServiceServer()
}

// UnimplementedGitServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGitServiceServer struct {
}

func (UnimplementedGitServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedGitServiceServer) StageFile(context.Context, *StageFileRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StageFile not implemented")
}
func (UnimplementedGitServiceServer) RevertFile(context.Context, *RevertFileRequest) (*RevertFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevertFile not implemented")
}
func (UnimplementedGitServiceServer) GetFileDiff(context.Context, *GetFileDiffRequest) (*GetFileDiffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileDiff not implemented")
}
func (UnimplementedGitServiceServer) mustEmbedUnimplementedGitServiceServer() {}

// UnsafeGitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitServiceServer will
// result in compilation errors.
type UnsafeGitServiceServer interface {
	mustEmbedUnimplementedGitServiceServer()
}

func RegisterGitServiceServer(s grpc.ServiceRegistrar, srv GitServiceServer) {
	s.RegisterService(&GitService_ServiceDesc, srv)
}

func _GitService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.git.GitService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_StageFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).StageFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.git.GitService/StageFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).StageFile(ctx, req.(*StageFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_RevertFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevertFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).RevertFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.git.GitService/RevertFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).RevertFile(ctx, req.(*RevertFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_GetFileDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).GetFileDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.git.GitService/GetFileDiff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).GetFileDiff(ctx, req.(*GetFileDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GitService_ServiceDesc is the grpc.ServiceDesc for GitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emdash.git.GitService",
	HandlerType: (*GitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _GitService_GetStatus_Handler,
		},
		{
			MethodName: "StageFile",
			Handler:    _GitService_StageFile_Handler,
		},
		{
			MethodName: "RevertFile",
			Handler:    _GitService_RevertFile_Handler,
		},
		{
			MethodName: "GetFileDiff",
			Handler:    _GitService_GetFileDiff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/git.proto",
}
