// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: api/proto/worktree.proto

package worktree

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WorktreeServiceClient is the client API for WorktreeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorktreeServiceClient interface {
	CreateWorktree(ctx context.Context, in *CreateWorktreeRequest, opts ...grpc.CallOption) (*CreateWorktreeResponse, error)
	ListWorktrees(ctx context.Context, in *ListWorktreesRequest, opts ...grpc.CallOption) (*ListWorktreesResponse, error)
	RemoveWorktree(ctx context.Context, in *RemoveWorktreeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetWorktreeStatus(ctx context.Context, in *GetWorktreeStatusRequest, opts ...grpc.CallOption) (*GetWorktreeStatusResponse, error)
	CreateWorktreeFromBranch(ctx context.Context, in *CreateWorktreeFromBranchRequest, opts ...grpc.CallOption) (*CreateWorktreeResponse, error)
}

type worktreeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorktreeServiceClient(cc grpc.ClientConnInterface) WorktreeServiceClient {
	return &worktreeServiceClient{cc}
}

func (c *worktreeServiceClient) CreateWorktree(ctx context.Context, in *CreateWorktreeRequest, opts ...grpc.CallOption) (*CreateWorktreeResponse, error) {
	out := new(CreateWorktreeResponse)
	err := c.cc.Invoke(ctx, "/emdash.worktree.WorktreeService/CreateWorktree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worktreeServiceClient) ListWorktrees(ctx context.Context, in *ListWorktreesRequest, opts ...grpc.CallOption) (*ListWorktreesResponse, error) {
	out := new(ListWorktreesResponse)
	err := c.cc.Invoke(ctx, "/emdash.worktree.WorktreeService/ListWorktrees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worktreeServiceClient) RemoveWorktree(ctx context.Context, in *RemoveWorktreeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/emdash.worktree.WorktreeService/RemoveWorktree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worktreeServiceClient) GetWorktreeStatus(ctx context.Context, in *GetWorktreeStatusRequest, opts ...grpc.CallOption) (*GetWorktreeStatusResponse, error) {
	out := new(GetWorktreeStatusResponse)
	err := c.cc.Invoke(ctx, "/emdash.worktree.WorktreeService/GetWorktreeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worktreeServiceClient) CreateWorktreeFromBranch(ctx context.Context, in *CreateWorktreeFromBranchRequest, opts ...grpc.CallOption) (*CreateWorktreeResponse, error) {
	out := new(CreateWorktreeResponse)
	err := c.cc.Invoke(ctx, "/emdash.worktree.WorktreeService/CreateWorktreeFromBranch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorktreeServiceServer is the server API for WorktreeService service.
// All implementations must embed UnimplementedWorktreeServiceServer
// for forward compatibility
type WorktreeServiceServer interface {
	CreateWorktree(context.Context, *CreateWorktreeRequest) (*CreateWorktreeResponse, error)
	ListWorktrees(context.Context, *ListWorktreesRequest) (*ListWorktreesResponse, error)
	RemoveWorktree(context.Context, *RemoveWorktreeRequest) (*emptypb.Empty, error)
	GetWorktreeStatus(context.Context, *GetWorktreeStatusRequest) (*GetWorktreeStatusResponse, error)
	CreateWorktreeFromBranch(context.Context, *CreateWorktreeFromBranchRequest) (*CreateWorktreeResponse, error)
	mustEmbedUnimplementedWorktreeServiceServer()
}

// UnimplementedWorktreeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWorktreeServiceServer struct {
}

func (UnimplementedWorktreeServiceServer) CreateWorktree(context.Context, *CreateWorktreeRequest) (*CreateWorktreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorktree not implemented")
}
func (UnimplementedWorktreeServiceServer) ListWorktrees(context.Context, *ListWorktreesRequest) (*ListWorktreesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorktrees not implemented")
}
func (UnimplementedWorktreeServiceServer) RemoveWorktree(context.Context, *RemoveWorktreeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveWorktree not implemented")
}
func (UnimplementedWorktreeServiceServer) GetWorktreeStatus(context.Context, *GetWorktreeStatusRequest) (*GetWorktreeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorktreeStatus not implemented")
}
func (UnimplementedWorktreeServiceServer) CreateWorktreeFromBranch(context.Context, *CreateWorktreeFromBranchRequest) (*CreateWorktreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorktreeFromBranch not implemented")
}
func (UnimplementedWorktreeServiceServer) mustEmbedUnimplementedWorktreeServiceServer() {}

// UnsafeWorktreeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorktreeServiceServer will
// result in compilation errors.
type UnsafeWorktreeServiceServer interface {
	mustEmbedUnimplementedWorktreeServiceServer()
}

func RegisterWorktreeServiceServer(s grpc.ServiceRegistrar, srv WorktreeServiceServer) {
	s.RegisterService(&WorktreeService_ServiceDesc, srv)
}

func _WorktreeService_CreateWorktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorktreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorktreeServiceServer).CreateWorktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.worktree.WorktreeService/CreateWorktree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorktreeServiceServer).CreateWorktree(ctx, req.(*CreateWorktreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorktreeService_ListWorktrees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorktreesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorktreeServiceServer).ListWorktrees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.worktree.WorktreeService/ListWorktrees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorktreeServiceServer).ListWorktrees(ctx, req.(*ListWorktreesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorktreeService_RemoveWorktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWorktreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorktreeServiceServer).RemoveWorktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.worktree.WorktreeService/RemoveWorktree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorktreeServiceServer).RemoveWorktree(ctx, req.(*RemoveWorktreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorktreeService_GetWorktreeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorktreeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorktreeServiceServer).GetWorktreeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.worktree.WorktreeService/GetWorktreeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorktreeServiceServer).GetWorktreeStatus(ctx, req.(*GetWorktreeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorktreeService_CreateWorktreeFromBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorktreeFromBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorktreeServiceServer).CreateWorktreeFromBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emdash.worktree.WorktreeService/CreateWorktreeFromBranch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorktreeServiceServer).CreateWorktreeFromBranch(ctx, req.(*CreateWorktreeFromBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorktreeService_ServiceDesc is the grpc.ServiceDesc for WorktreeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorktreeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emdash.worktree.WorktreeService",
	HandlerType: (*WorktreeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorktree",
			Handler:    _WorktreeService_CreateWorktree_Handler,
		},
		{
			MethodName: "ListWorktrees",
			Handler:    _WorktreeService_ListWorktrees_Handler,
		},
		{
			MethodName: "RemoveWorktree",
			Handler:    _WorktreeService_RemoveWorktree_Handler,
		},
		{
			MethodName: "GetWorktreeStatus",
			Handler:    _WorktreeService_GetWorktreeStatus_Handler,
		},
		{
			MethodName: "CreateWorktreeFromBranch",
			Handler:    _WorktreeService_CreateWorktreeFromBranch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/worktree.proto",
}
